import { NuqsAdapter } from "nuqs/adapters/next/app";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/query-provider";

import { cn } from "@/lib/utils";

import { suppressWarnings } from "@/lib/utils";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  suppressWarnings();
  // console.log(" Started 🏁🏁🏁");

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
        suppressHydrationWarning
      >
        <NuqsAdapter>
          <QueryProvider>
            <Toaster />
            {children}
          </QueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
